export const GET_CITIES = 'GET_CITIES'
export const SET_TO_CART = 'SET_TO_CART'
export const CLEAN_CART = 'CLEAN_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
